SELECT A.ANIMAL_ID, A.NAME
FROM ANIMAL_OUTS A,
     (SELECT O.ANIMAL_ID
      FROM ANIMAL_OUTS O
               LEFT JOIN ANIMAL_INS I ON O.ANIMAL_ID = I.ANIMAL_ID
      WHERE I.ANIMAL_ID IS NULL) R
WHERE A.ANIMAL_ID = R.ANIMAL_ID
ORDER BY A.ANIMAL_ID;
